const groups = [
  // { groupId: 0, groupName: "", groupScore: 0 },
  { groupId: 1, groupName: "机关联合队", groupScore: 0 },
  { groupId: 2, groupName: "洋浦海关队", groupScore: 0 },
  { groupId: 3, groupName: "海口美兰机场海关队", groupScore: 0 },
  { groupId: 4, groupName: "椰城海关队", groupScore: 0 },
  { groupId: 5, groupName: "三亚海关队", groupScore: 0 },
  { groupId: 6, groupName: "马村港海关队", groupScore: 0 },
  { groupId: 7, groupName: "事业单位联合队", groupScore: 0 },
  { groupId: 8, groupName: "八所海关队", groupScore: 0 },
  { groupId: 9, groupName: "海口港海关队", groupScore: 0 },
  { groupId: 10, groupName: "博鳌机场海关、文昌海关联合队", groupScore: 0 },
];

const players = [
  { id: 0, name: "", groupId: 0, score: 0, part: "", groupName: "比赛准备开始" },
  { id: 1, name: "杜婉婧（教育处）", groupName: "机关联合队", groupId: 1, score: 0, part: "第一环节" },
  { id: 2, name: "冯尔策（口岸监管处）", groupName: "机关联合队", groupId: 1, score: 0, part: "第二环节" },
  { id: 3, name: "陈瑛琦（统计处）", groupName: "机关联合队", groupId: 1, score: 0, part: "第三环节" },
  { id: 4, name: "张绮", groupName: "洋浦海关队", groupId: 2, score: 0, part: "第一环节" },
  { id: 5, name: "陈家蕙", groupName: "洋浦海关队", groupId: 2, score: 0, part: "第二环节" },
  { id: 6, name: "周爱玉", groupName: "洋浦海关队", groupId: 2, score: 0, part: "第三环节" },
  { id: 7, name: "韩金璐", groupName: "海口美兰机场海关队", groupId: 3, score: 0, part: "第一环节" },
  { id: 8, name: "辜振成", groupName: "海口美兰机场海关队", groupId: 3, score: 0, part: "第二环节" },
  { id: 9, name: "鲍莹", groupName: "海口美兰机场海关队", groupId: 3, score: 0, part: "第三环节" },
  { id: 10, name: "沙尔哈提·哈力木哈则", groupName: "椰城海关队", groupId: 4, score: 0, part: "第一环节" },
  { id: 11, name: "冯雨萱", groupName: "椰城海关队", groupId: 4, score: 0, part: "第二环节" },
  { id: 12, name: "占若", groupName: "椰城海关队", groupId: 4, score: 0, part: "第三环节" },
  { id: 13, name: "吴昊", groupName: "三亚海关队", groupId: 5, score: 0, part: "第一环节" },
  { id: 14, name: "王纯豪", groupName: "三亚海关队", groupId: 5, score: 0, part: "第二环节" },
  { id: 15, name: "李琳", groupName: "三亚海关队", groupId: 5, score: 0, part: "第三环节" },
  { id: 16, name: "胡慧宣", groupName: "马村港海关队", groupId: 6, score: 0, part: "第一环节" },
  { id: 17, name: "林详松", groupName: "马村港海关队", groupId: 6, score: 0, part: "第二环节" },
  { id: 18, name: "张丹", groupName: "马村港海关队", groupId: 6, score: 0, part: "第三环节" },
  { id: 19, name: "蒙威任", groupName: "事业单位联合队", groupId: 7, score: 0, part: "第一环节" },
  { id: 20, name: "黄杰英", groupName: "事业单位联合队", groupId: 7, score: 0, part: "第二环节" },
  { id: 21, name: "万培弟", groupName: "事业单位联合队", groupId: 7, score: 0, part: "第三环节" },
  { id: 22, name: "吴琪", groupName: "八所海关队", groupId: 8, score: 0, part: "第一环节" },
  { id: 23, name: "林斯鹏", groupName: "八所海关队", groupId: 8, score: 0, part: "第二环节" },
  { id: 24, name: "翁可聿", groupName: "八所海关队", groupId: 8, score: 0, part: "第三环节" },
  { id: 25, name: "林华婷", groupName: "海口港海关队", groupId: 9, score: 0, part: "第一环节" },
  { id: 26, name: "刘宸", groupName: "海口港海关队", groupId: 9, score: 0, part: "第二环节" },
  { id: 27, name: "王昱棋", groupName: "海口港海关队", groupId: 9, score: 0, part: "第三环节" },
  {
    id: 28,
    name: "黄功（文昌海关）",
    groupName: "博鳌机场海关、文昌海关联合队",
    groupId: 10,
    score: 0,
    part: "第一环节",
  },
  {
    id: 29,
    name: "纪冰冰（文昌海关）",
    groupName: "博鳌机场海关、文昌海关联合队",
    groupId: 10,
    score: 0,
    part: "第二环节",
  },
  {
    id: 30,
    name: "李鸿浩（博鳌机场海关）",
    groupName: "博鳌机场海关、文昌海关联合队",
    groupId: 10,
    score: 0,
    part: "第三环节",
  },
];

export { groups, players };
